# Generated by Django 4.2.6 on 2024-01-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosti_sandesh', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Message',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
